Filter-Rule ::= < AVP Header: 509 >
	[ Filter-Rule-Precedence ]
	; Condition part of a Rule
	; ------------------------
	[ Classifier ]
	* [ Time-Of-Day-Condition ]
	[ Treatment-Action ]
	[ QoS-Semantics ]
	[ QoS-Profile-Template ]
	[ QoS-Parameters ]
	[ Excess-Treatment ]
	* [ AVP ]
