   Excess-Treatment ::= < AVP Header: 577 >
                        { Treatment-Action }
                        [ QoS-Profile-Template ]
                        [ QoS-Parameters ]
                      * [ AVP ]
