< Location-Report-Request> ::=    < Diameter Header: 8388621, REQ, PXY, 16777255 >
    < Session-Id >
    [ Vendor-Specific-Application-Id ]
    { Auth-Session-State }
    { Origin-Host }
    { Origin-Realm }
    { Destination-Host }
    { Destination-Realm }
    { Location-Event }
    [ LCS-EPS-Client-Name ]
    [ User-Name ]
    [ MSISDN]
    [ IMEI ]
    [ Location-Estimate ]
    [ Accuracy-Fulfilment-Indicator ]
    [ Age-Of-Location-Estimate ]
    [ Velocity-Estimate ]
    [ EUTRAN-Positioning-Data ]
    [ ECGI]
    [ GERAN-Positioning-Info ]
    [ Cell-Global-Identity ]
    [ UTRAN-Positioning-Info ]
    [ Service-Area-Identity ]
    [ LCS-Service-Type-ID ]
    [ Pseudonym-Indicator ]
    [ LCS-QoS-Class ]
    [ Serving-Node ]
    [ LRR-Flags ]
    [ LCS-Reference-Number ]
    [ Deferred-MT-LR-Data]
    [ GMLC-Address ]
    [ Reporting-Amount ]
    [ Periodic-LDR-Information ]
    [ ESMLC-Cell-Info ]
    [ 1xRTT-RCID ] ]
    [ Delayed-Location-Reporting-Data ]
    [ Civic-Address ]
    [ Barometric-Pressure ]
    *[ Supported-Features ]
    *[ AVP ]
    *[ Proxy-Info ]
    *[ Route-Record ]
