< Send-Routing-Info-for-SM-Request > ::= < Diameter Header: 8388647, REQ, PXY, 16777312 >
	 < Session-Id >
	[ DRMP ]
	[ Vendor-Specific-Application-Id ] 
	{ Auth-Session-State }
	{ Origin-Host }
	{ Origin-Realm }
	[ Destination-Host ]
	{ Destination-Realm }
	[ MSISDN ]
	[ User-Name ]
	[ SMSMI-Correlation-ID ]
	*[ Supported-Features ]
	[ SC-Address ]
	[ SM-RP-MTI ]
	[ SM-RP-SMEA ]
	[ SRR-Flags ]
	[ SM-Delivery-Not-Intended ]
	*[ AVP ]
	*[ Proxy-Info ]
	*[ Route-Record ]
