< User-Data-Request> ::= < Diameter Header: 306, REQ, PXY, 16777217 >
< Session-Id >
[ DRMP ]
{ Vendor-Specific-Application-Id }
{ Auth-Session-State }
{ Origin-Host }
{ Origin-Realm }
[ Destination-Host ]
{ Destination-Realm }
*[ Supported-Features ]
{ User-Identity }
[ Wildcarded-Public-Identity ]
[ Wildcarded-IMPU ]
[ Server-Name ]
*[ Service-Indication ]
*{ Data-Reference }
*[ Identity-Set ]
[ Requested-Domain ]
[ Current-Location ]
*[ DSAI-Tag ]
[ Session-Priority ]
[ User-Name ]
[ Requested-Nodes ]
[ Serving-Node-Indication ]
[ Pre-paging-Supported ]
[ Local-Time-Zone-Indication ] [ UDR-Flags ]
[ Call-Reference-Info ]
[ OC-Supported-Features ]
*[ AVP ]
*[ Proxy-Info ]
*[ Route-Record ]
