< Cancel-Location-Answer> ::= < Diameter Header: 317, PXY, 16777251 > 
< Session-Id > 
[ DRMP ]  
[ Vendor-Specific-Application-Id ] 
*[ Supported-Features ] 
[ Result-Code ] 
[ Experimental-Result ]  
{ Auth-Session-State } 
{ Origin-Host } 
{ Origin-Realm } 
*[ AVP ] 
[ Failed-AVP ] 
*[ Proxy-Info ] 
*[ Route-Record ] 