< Alert-Service-Centre-Request > ::= < Diameter Header: 8388648, REQ, PXY, 16777312 > 
	< Session-Id >
	[ DRMP ]
	[ Vendor-Specific-Application-Id ] 
	{ Auth-Session-State }
	{ Origin-Host }
	{ Origin-Realm }
	[ Destination-Host ]
	{ Destination-Realm }
	{ SC-Address }
	{ User-Id }
	[ SMSMI-Correlation-ID ]
	[ Maximum-UE-Availability-Time ]
	[ SMS-GMSC-Alert-Event ]
	[ Serving-Node ]
	*[ Supported-Features ]
	*[ AVP ]
	*[ Proxy-Info ]
	*[ Route-Record ]
