<LCS-Routing-Info-Request> ::= < Diameter Header: 8388622, REQ, PXY, 16777291 >
    < Session-Id >
    [ Vendor-Specific-Application-Id ]
    { Auth-Session-State }
    { Origin-Host }
    { Origin-Realm }
    [ Destination-Host ]
    { Destination-Realm }
    [ User-Name ]
    [ MSISDN ]
    [ GMLC-Number ]
    *[ Supported-Features ]
    *[ Proxy-Info ]
    *[ Route-Record ]
    *[ AVP ]
