< Subscriber-Information-Request> ::= < Diameter Header: 8388641, REQ, PXY, 16777310 > < Session-Id >
[ DRMP ]
{ Auth-Session-State }
{ Origin-Host }
{ Origin-Realm }
[ Destination-Host ]
{ Destination-Realm }
{ User-Identifier }
[ Service-ID ]
[ SCS-Identity ]
[ Service-Parameters ]
{ SIR-Flags }
[ OC-Supported-Features ]
*[ Supported-Features ]
*[ Proxy-Info ]
*[ Route-Record ]
*[ AVP ]