< Send-Routing-Info-for-SM-Answer > ::= < Diameter Header: 8388647, PXY, 16777312 > 
	< Session-Id >
	[ DRMP ]
	[ Vendor-Specific-Application-Id ]
	[ Result-Code ]
	[ Experimental-Result ]
	{ Auth-Session-State }
	{ Origin-Host }
	{ Origin-Realm }
	[ User-Name ]
	*[ Supported-Features ]
	[ Serving-Node ]
	[ Additional-Serving-Node ]
	[ LMSI ]
	[ User-Identifier ]
	[ MWD-Status ]
	[ MME-Absent-User-Diagnostic-SM ]
	[ MSC-Absent-User-Diagnostic-SM ]
	[ SGSN-Absent-User-Diagnostic-SM ]
	*[ AVP ]
	[ Failed-AVP ]
	*[ Proxy-Info ]
	*[ Route-Record ]
