Subscription-Data ::= <AVP header: 1400 10415>
[ Subscriber-Status ] 
[ MSISDN ]
[ A-MSISDN ]
[ STN-SR ]
[ ICS-Indicator ]
[ Network-Access-Mode ]
[ Operator-Determined-Barring ]
[ HPLMN-ODB ]
*10[ Regional-Subscription-Zone-Code ]
[ Access-Restriction-Data ]
[ APN-OI-Replacement ]
[ LCS-Info ]
[ Teleservice-List ]
*[ Call-Barring-Info ]
[ 3GPP-Charging-Characteristics ]
[ AMBR ]
[ APN-Configuration-Profile ]
[ RAT-Frequency-Selection-Priority-ID ]
[ Trace-Data]
[ GPRS-Subscription-Data ]
*[ CSG-Subscription-Data ]
[ Roaming-Restricted-Due-To-Unsupported-Feature ]
 [ Subscribed-Periodic-RAU-TAU-Timer ]
[ MPS-Priority ]
[ VPLMN-LIPA-Allowed ]
[ Relay-Node-Indicator ]
[ MDT-User-Consent ]
[ Subscribed-VSRVCC ]
[ ProSe-Subscription-Data ]
[ Subscription-Data-Flags ]
*[ Adjacent-Access-Restriction-Data ]
[ DL-Buffering-Suggested-Packet-Count ]
*[ IMSI-Group-Id ]
[ UE-Usage-Type ]
*[ AESE-Communication-Pattern ]
*[ Monitoring-Event-Configuration ]
[ Emergency-Info ]
[ V2X-Subscription-Data ]
*[ eDRX-Cycle-Length ]
[ External-Identifier ]
[ Active-Time ]
*[ AVP ]