MDT-Configuration ::= <AVP header: 1622 10415>
{ Job-Type }
[ Area-Scope ]
[ List-Of-Measurements ]
[ Reporting-Trigger ]
[ Report-Interval ]
[ Report-Amount ]
[ Event-Threshold-RSRP ]
[ Event-Threshold-RSRQ ]
[ Logging-Interval ]
[ Logging-Duration ]
[ Measurement-Period-LTE ]
[ Measurement-Period-UMTS ]
[ Collection-Period-RRM-LTE ]
[ Collection-Period-RRM-UMTS ] 
[ Positioning-Method ]
[ Measurement-Quantity]
[ Event-Threshold-Event-1F ]
[ Event-Threshold-Event-1I ]
*[ MDT-Allowed-PLMN-Id ]
*[ MBSFN-Area ]
*[ AVP ]
