Serving-Node ::=<AVP header: 2401 10415>
[ SGSN-Number ]
[ SGSN-Name ]
[ SGSN-Realm ]
[ MME-Name ]
[ MME-Realm ]
[ MSC-Number ]
[ 3GPP-AAA-Server-Name ] 
[ LCS-Capabilities-Sets ]
[ GMLC-Address ]
*[AVP]
