MME-Location-Information ::= <AVP header: 1600 10415>
[E-UTRAN-Cell-Global-Identity]
[Tracking-Area-Identity]
[Geographical-Information]
[Geodetic-Information]
[Current-Location-Retrieved]
[Age-Of-Location-Information]
[User-CSG-Information]
[ eNodeB-ID ]
[Extended-eNodeB-ID]
*[AVP]