Monitoring-Event-Report::= <AVP header: 3123 10415>
{ SCEF-Reference-ID }
[ SCEF-ID ]
[Visited-PLMN-Id]
[Roaming-Information]
[IMEI-Change]
[Reachability-Information]
[EPS-Location-Information]
[Monitoring-Type]
[Event-Handling]
* [Service-Report]
[Loss-Of-Connectivity-Reason]
[Idle-Status-Indication]
*[AVP]
