
COMMAND(UMDiameterPacketCER)
COMMAND(UMDiameterPacketCEA)
COMMAND(UMDiameterPacketDWR)
COMMAND(UMDiameterPacketDWA)
COMMAND(UMDiameterPacketSTR)
COMMAND(UMDiameterPacketSTA)
COMMAND(UMDiameterPacketRAR)
COMMAND(UMDiameterPacketRAA)
COMMAND(UMDiameterPacketACR)
COMMAND(UMDiameterPacketACA)
COMMAND(UMDiameterPacketDPR)
COMMAND(UMDiameterPacketDPA)
COMMAND(UMDiameterPacketASA)
COMMAND(UMDiameterPacketASR)
COMMAND(UMDiameterPacketCUR)
COMMAND(UMDiameterPacketCUA)
