< ME-Identity-Check-Request > ::= < Diameter Header: 324, REQ, PXY, 16777252 > 
 < Session-Id > 
[ DRMP ] 
 [ Vendor-Specific-Application-Id ] 
{ Auth-Session-State } 
 { Origin-Host } 
{ Origin-Realm } 
[ Destination-Host ] 
 { Destination-Realm } 
{ Terminal-Information } 
[ User-Name ] 
*[ AVP ] 
 *[ Proxy-Info ] 
*[ Route-Record ] 