< Insert-Subscriber-Data-Answer> ::=  < Diameter Header: 319, PXY, 16777251 > ; TS 29.272 Section 7.2.10. App can also be 16777308
< Session-Id > 
[ DRMP ] 
[ Vendor-Specific-Application-Id ] 
*[ Supported-Features ] 
[ Result-Code ] 
[ Experimental-Result ] 
{ Auth-Session-State } 
{ Origin-Host } 
{ Origin-Realm } 
[ IMS-Voice-Over-PS-Sessions-Supported ] 
[ Last-UE-Activity-Time ] 
 [ RAT-Type ] 
[ IDA-Flags ] 
[ EPS-User-State ] 
[ EPS-Location-Information ] 
[Local-Time-Zone ] 
[ Supported-Services ] 
*[ Monitoring-Event-Report ] 
*[ Monitoring-Event-Config-Status ] 
*[ AVP ] 
[ Failed-AVP ] 
*[ Proxy-Info ] 
*[ Route-Record ] 
