< Notify-Answer> ::= < Diameter Header: 323, PXY, 16777251 > TS 29.272 Section 7.2.18
< Session-Id > 
[ DRMP ] 
[ Vendor-Specific-Application-Id ] 
[ Result-Code ] 
[ Experimental-Result ]  
{ Auth-Session-State } 
{ Origin-Host } 
{ Origin-Realm } 
[ OC-Supported-Features ] 
[ OC-OLR ] 
*[ Load ] 
*[ Supported-Features ] 
*[ AVP ] 
[ Failed-AVP ] 
*[ Proxy-Info ] 
*[ Route-Record ]
