< Cancel-VCSG-Location-Request> ::= < Diameter Header: 8388642, REQ, PXY,  > 
< Session-Id > 
[ DRMP ] 
[ Vendor-Specific-Application-Id ] 
{ Auth-Session-State } 
{ Origin-Host } 
{ Origin-Realm } 
{ Destination-Host } 
{ Destination-Realm } 
{ User-Name } 
*[Supported-Features ] 
{ Cancellation-Type } 
*[ AVP ] 
*[ Proxy-Info ] 
*[ Route-Record ] 
