< Reset-Answer> ::=  < Diameter Header: 322, PXY, 16777251 > ; TS 29.272 section 7.2.16. App also 16777308
< Session-Id > 
[ DRMP ] 
[ Vendor-Specific-Application-Id ] 
*[ Supported-Features ] 
[ Result-Code ] 
[ Experimental-Result ] 
{ Auth-Session-State } 
{ Origin-Host } 
{ Origin-Realm } 
*[ AVP ] 
[ Failed-AVP ] 
*[ Proxy-Info ] 
*[ Route-Record ] 
