//
// automatically generated incldues from diametr-avp-gen
//
#import <ulibdiameter/UMDiameterAvpUser_Name.h>
#import <ulibdiameter/UMDiameterAvpFramed_IP_Address.h>
#import <ulibdiameter/UMDiameterAvpClass.h>
#import <ulibdiameter/UMDiameterAvpSession_Timeout.h>
#import <ulibdiameter/UMDiameterAvpProxy_State.h>
#import <ulibdiameter/UMDiameterAvpAcct_Session_Id.h>
#import <ulibdiameter/UMDiameterAvpAcct_Multi_Session_Id.h>
#import <ulibdiameter/UMDiameterAvpEvent_Timestamp.h>
#import <ulibdiameter/UMDiameterAvpAcct_Interim_Interval.h>
#import <ulibdiameter/UMDiameterAvpChargeable_User_Identity.h>
#import <ulibdiameter/UMDiameterAvpFramed_Interface_Id.h>
#import <ulibdiameter/UMDiameterAvpFramed_IPv6_Prefix.h>
#import <ulibdiameter/UMDiameterAvpMIP6_Feature_Vector.h>
#import <ulibdiameter/UMDiameterAvpMIP6_Home_Link_Prefix.h>
#import <ulibdiameter/UMDiameterAvpHost_IP_Address.h>
#import <ulibdiameter/UMDiameterAvpAuth_Application_Id.h>
#import <ulibdiameter/UMDiameterAvpAcct_Application_Id.h>
#import <ulibdiameter/UMDiameterAvpVendor_Specific_Application_Id.h>
#import <ulibdiameter/UMDiameterAvpRedirect_Host_Usage.h>
#import <ulibdiameter/UMDiameterAvpRedirect_Max_Cache_Time.h>
#import <ulibdiameter/UMDiameterAvpSession_Id.h>
#import <ulibdiameter/UMDiameterAvpOrigin_Host.h>
#import <ulibdiameter/UMDiameterAvpSupported_Vendor_Id.h>
#import <ulibdiameter/UMDiameterAvpVendor_Id.h>
#import <ulibdiameter/UMDiameterAvpFirmware_Revision.h>
#import <ulibdiameter/UMDiameterAvpResult_Code.h>
#import <ulibdiameter/UMDiameterAvpProduct_Name.h>
#import <ulibdiameter/UMDiameterAvpSession_Binding.h>
#import <ulibdiameter/UMDiameterAvpSession_Server_Failover.h>
#import <ulibdiameter/UMDiameterAvpMulti_Round_Time_Out.h>
#import <ulibdiameter/UMDiameterAvpDisconnect_Cause.h>
#import <ulibdiameter/UMDiameterAvpAuth_Request_Type.h>
#import <ulibdiameter/UMDiameterAvpAuth_Grace_Period.h>
#import <ulibdiameter/UMDiameterAvpAuth_Session_State.h>
#import <ulibdiameter/UMDiameterAvpOrigin_State_Id.h>
#import <ulibdiameter/UMDiameterAvpFailed_AVP.h>
#import <ulibdiameter/UMDiameterAvpProxy_Host.h>
#import <ulibdiameter/UMDiameterAvpError_Message.h>
#import <ulibdiameter/UMDiameterAvpRoute_Record.h>
#import <ulibdiameter/UMDiameterAvpDestination_Realm.h>
#import <ulibdiameter/UMDiameterAvpProxy_Info.h>
#import <ulibdiameter/UMDiameterAvpRe_Auth_Request_Type.h>
#import <ulibdiameter/UMDiameterAvpAccounting_Sub_Session_Id.h>
#import <ulibdiameter/UMDiameterAvpAuthorization_Lifetime.h>
#import <ulibdiameter/UMDiameterAvpRedirect_Host.h>
#import <ulibdiameter/UMDiameterAvpDestination_Host.h>
#import <ulibdiameter/UMDiameterAvpError_Reporting_Host.h>
#import <ulibdiameter/UMDiameterAvpTermination_Cause.h>
#import <ulibdiameter/UMDiameterAvpOrigin_Realm.h>
#import <ulibdiameter/UMDiameterAvpExperimental_Result.h>
#import <ulibdiameter/UMDiameterAvpExperimental_Result_Code.h>
#import <ulibdiameter/UMDiameterAvpInband_Security_Id.h>
#import <ulibdiameter/UMDiameterAvpDRMP.h>
#import <ulibdiameter/UMDiameterAvpMIP_Mobile_Node_Address.h>
#import <ulibdiameter/UMDiameterAvpMIP_Home_Agent_Address.h>
#import <ulibdiameter/UMDiameterAvpMIP_MN_AAA_SPI.h>
#import <ulibdiameter/UMDiameterAvpMIP_Session_Key.h>
#import <ulibdiameter/UMDiameterAvpMIP_Replay_Mode.h>
#import <ulibdiameter/UMDiameterAvpMIP_Home_Agent_Host.h>
#import <ulibdiameter/UMDiameterAvpMIP_MSA_Lifetime.h>
#import <ulibdiameter/UMDiameterAvpAccounting_Record_Type.h>
#import <ulibdiameter/UMDiameterAvpAccounting_Realtime_Required.h>
#import <ulibdiameter/UMDiameterAvpAccounting_Record_Number.h>
#import <ulibdiameter/UMDiameterAvpMIP6_Agent_Info.h>
#import <ulibdiameter/UMDiameterAvpMIP_Careof_Address.h>
#import <ulibdiameter/UMDiameterAvpMIP_Authenticator.h>
#import <ulibdiameter/UMDiameterAvpMIP_MAC_Mobility_Data.h>
#import <ulibdiameter/UMDiameterAvpMIP_Timestamp.h>
#import <ulibdiameter/UMDiameterAvpMIP_MN_HA_SPI.h>
#import <ulibdiameter/UMDiameterAvpService_Selection.h>
#import <ulibdiameter/UMDiameterAvpMIP6_Auth_Mode.h>
#import <ulibdiameter/UMDiameterAvpLine_Identifier.h>
#import <ulibdiameter/UMDiameterAvpQoS_Resources.h>
#import <ulibdiameter/UMDiameterAvpFilter_Rule.h>
#import <ulibdiameter/UMDiameterAvpTime_Of_Day_Start.h>
#import <ulibdiameter/UMDiameterAvpTime_Of_Day_End.h>
#import <ulibdiameter/UMDiameterAvpDay_Of_Week_Mask.h>
#import <ulibdiameter/UMDiameterAvpQoS_Profile_Id.h>
#import <ulibdiameter/UMDiameterAvpQoS_Profile_Template.h>
#import <ulibdiameter/UMDiameterAvpQoS_Capability.h>

