//
// automatically generated incldues from diametr-avp-gen
//
#import <ulibdiameter/AVP/base/UMDiameterAvpUser_Name.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpFramed_IP_Address.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpClass.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpSession_Timeout.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpProxy_State.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpAcct_Session_Id.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpAcct_Multi_Session_Id.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpEvent_Timestamp.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpAcct_Interim_Interval.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpChargeable_User_Identity.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpFramed_Interface_Id.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpFramed_IPv6_Prefix.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP6_Feature_Vector.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP6_Home_Link_Prefix.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpHost_IP_Address.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpAuth_Application_Id.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpAcct_Application_Id.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpVendor_Specific_Application_Id.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpRedirect_Host_Usage.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpRedirect_Max_Cache_Time.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpSession_Id.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpOrigin_Host.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpSupported_Vendor_Id.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpVendor_Id.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpFirmware_Revision.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpResult_Code.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpProduct_Name.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpSession_Binding.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpSession_Server_Failover.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMulti_Round_Time_Out.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpDisconnect_Cause.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpAuth_Request_Type.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpAuth_Grace_Period.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpAuth_Session_State.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpOrigin_State_Id.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpFailed_AVP.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpProxy_Host.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpError_Message.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpRoute_Record.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpDestination_Realm.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpProxy_Info.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpRe_Auth_Request_Type.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpAccounting_Sub_Session_Id.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpAuthorization_Lifetime.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpRedirect_Host.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpDestination_Host.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpError_Reporting_Host.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpTermination_Cause.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpOrigin_Realm.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpExperimental_Result.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpExperimental_Result_Code.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpInband_Security_Id.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpDRMP.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP_Mobile_Node_Address.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP_Home_Agent_Address.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP_MN_AAA_SPI.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP_Session_Key.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP_Replay_Mode.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP_Home_Agent_Host.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP_MSA_Lifetime.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpAccounting_Record_Type.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpAccounting_Realtime_Required.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpAccounting_Record_Number.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP6_Agent_Info.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP_Careof_Address.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP_Authenticator.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP_MAC_Mobility_Data.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP_Timestamp.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP_MN_HA_SPI.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpService_Selection.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpMIP6_Auth_Mode.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpLine_Identifier.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpQoS_Resources.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpFilter_Rule.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpTime_Of_Day_Start.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpTime_Of_Day_End.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpDay_Of_Week_Mask.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpQoS_Profile_Id.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpQoS_Profile_Template.h>
#import <ulibdiameter/AVP/base/UMDiameterAvpQoS_Capability.h>

